# -*- coding: utf-8 -*-
"""students_record_system.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XpVA9pbBIZ5q9QI5tdOehMaEFh6sgXCx
"""

import json
import os

class Student_record_management:
    def __init__(self, filename='students_record.json'):
        self.filename = filename
        self.records = self.load_records()
        self.menu()


    def menu(self):
        print('1. Add Student')
        print('2. View All Students')
        print('3. Update Student')
        print('4. Delete Student')
        print('5. Exit')

        while True:
            try:
                user_input = int(input('Enter the choice(1-5): '))
                if user_input == 1:
                    self.add_student()
                elif user_input == 2:
                    self.view_student()
                elif user_input == 3:
                    self.update_details()
                elif user_input == 4:
                    self.delete_student()
                elif user_input == 5:
                    self.save_details()
                    print('Exiting from Record Management System.')
                    break
                else:
                    print('Invalid choice. please choose the correct on.')
            except ValueError:
                print('Invalid integer value.')
            except Exception as e:
                print(f"some Error occcured: {e}")

    def add_student(self):

        std_name = input('Enter student name: ')
        if not std_name:
            print('Name is empty.')
            return

        std_id = None
        while True:
            try:
                std_id = int(input('Enter student id: '))
                if std_id in self.records:
                    print(f'{std_id} exists in student record system')
                else:
                    break
            except ValueError:
                print(' please enter an integer ID.')
            except Exception as e:
                print(f"some Error occured: {e}")

        student_record = {
            'Student Name': std_name,
            'Student ID': std_id,
            'Marks': {}
        }

        while True:
            marks_input = input('Enter 4 marks (ex- 80 75 90 65): ')
            if not isinstance(marks_input, str):
                print("Invalid input.")
                continue
            try:
                std_marks = list(map(int, marks_input.split()))
                if len(std_marks) == 4:
                    student_record['Marks'] = {
                        'Bengali' :std_marks[0],
                        'Math' : std_marks[1],
                        'Python' : std_marks[2],
                        'Java' :std_marks[3]
                        }
                    break
                else:
                    print('4 subjects only.')
            except ValueError:
                print('please enter Integer marks.')
            except Exception as e:
                print(f"some Error occured: {e}")

        self.records[std_id] = student_record

        print(f'{std_name} Added sucessfully.')
        self.save_details()



    def update_details(self):

        self.view_student()
        if not self.records :
            print('there is no records to update.')
            return

        while True:
            try:
                std_id_to_update = int(input('Enter ID to update: '))
                if std_id_to_update in self.records:
                    break
                else:
                    print(f'{std_id_to_update} not found.')
            except ValueError:
                print('Integer ID.')
            except Exception as e:
                print(f"Error: {e}")

        current_student_record = self.records[std_id_to_update]

        new_name = input(f"New name: ")
        if new_name:
            current_student_record['Student Name'] = new_name
            print('Name updated sucessfully.')

        while True:
                marks_input = input('Enter new 4 marks (ex- 80 75 90 65): ')
                if not isinstance(marks_input, str):
                    print('Invalid input.')
                    continue
                try:
                    std_marks = list(map(int, marks_input.split()))
                    if len(std_marks) == 4:
                        current_student_record['Marks'] = {
                            'Bengali' :std_marks[0],
                            'Math' : std_marks[1],
                            'Python' : std_marks[2],
                            'Java' :std_marks[3]
                        }
                        print('Marks updated sucessfully.')
                        break
                    else:
                        print('4 subjects allowed only.')
                except ValueError:
                    print('please enter Integer marks.')
                except Exception as e:
                    print(f"some Error Occured: {e}")

        print(f'{current_student_record["Student Name"]} updated sucessfully.')
        self.save_details()


    def view_student(self):
        if self.records:
            for std_id_key, details in self.records.items():
                if isinstance(std_id_key, int) and isinstance(details, dict) :
                    print(f'Student ID: {details.get("Student ID", "N/A")}')
                    print(f"Name: {details.get('Student Name', 'N/A')}")
                    print(f"Marks: {details.get('Marks', {})}")
        else:
            print("there is no records.")

    def searching_details(self):
        search_id = None
        while True:
            try:
                search_id = int(input('Enter Student ID to search: '))
                break
            except ValueError:
                print('enter Integer ID.')
            except Exception as e:
                print(f"some Error occured : {e}")

        if search_id in self.records:
            details = self.records[search_id]
            print(f'\nStudent ID: {details.get("Student ID", "N/A")}')
            print(f"Name: {details.get('Student Name', 'N/A')}")
            print(f"Marks: {details.get('Marks', {})}")
        else:
            print(f'{search_id} not found in records.')


    def delete_student(self):
        self.view_student()

        if not self.records:
            print('there is no Records to show.')
            return

        while True:
            try:
                delete_std_id = int(input('Enter student ID to delete: '))
                if delete_std_id in self.records:
                    del self.records[delete_std_id]
                    self.save_details()
                    print(f'{delete_std_id} deleted sucessfully.')
                    break
                else:
                    print(f'{delete_std_id} not found in Student records.')
            except ValueError:
                print('please enter Integer ID.')
            except Exception as e:
                print(f'some Error occured: {e}')


    def save_details(self):
        with open(self.filename, 'w') as f:
            json.dump(self.records, f, indent=4)
        print('Record Saved successfully.')

    def load_records(self):
        if os.path.exists(self.filename):
            with open(self.filename, 'r') as f:
                return json.load(f)
        return {}

student = Student_record_management()